#!/usr/bin/env zsh
# fn/z4b-forward-zword
# Tokenizer word forward

local word buf
repeat ${NUMERIC:-1}; do
  buf=$PREBUFFER$BUFFER
  for word in ${(Z:n:)buf} ''; do
    (( $#buf < $#RBUFFER )) && break
    buf=${${buf##[[:space:]]#}:$#word}
  done
  CURSOR=$(($#BUFFER - $#buf))
  # Stub: _z4b_cursor_max
  # if (( CURSOR > _z4b_cursor_max() )); then
  #   (( --CURSOR ))
  # fi
done
return 0
